boostorg/container

include/boost/container/detail/advanced_insert_int.hpp
They cause MSVC to print warnings every time this file is included if on a Japanese locale. (Note that Github diff isn't displaying the old characters.)
=> Replace "smart quotes" Latin1 characters

include/boost/container/stable_vector.hpp
See http://stackoverflow.com/q/29727368/2756719; the bit-twiddling version is not equivalent to the original `return (index_size ? (index_size - ExtraPointers + extra_capacity) : index_size);`; it ends up subtracting, rather than adding, extra_capacity.
=> Fix bug in stable_vector::capacity()

include/boost/container/detail/std_fwd.hpp
The code should not assume that libc++ is only ever used with Clang.
Fixes issue #11380, https://svn.boost.org/trac/boost/ticket/11380
=> Fix std:: forward declaration compile error on GCC with libc++

bench/detail/varray.hpp, bench/detail/varray_util.hpp, bench/varray.hpp
The macro `BOOST_NO_RVALUE_REFERENCES` was deprecated in boost 1.51.0, and was replaced by `BOOST_NO_CXX11_RVALUE_REFERENCES`.  It's been 8 releases since these were deprecated, and I'd like to remove them
Replace all uses of `BOOST_NO_RVALUE_REFERENCES` with `BOOST_NO_CXX11_RVALUE_REFERENCES`. 
No functionality change.
=> Remove use of deprecated macros; use replacements

src/dlmalloc_ext_2_8_6.c
DL_SIZE_IMPL also dereference addr, so call inside Null check statement.
=> DL_SIZE_IMPL also dereference addr

include/boost/container/throw_exception.hpp
Make sure `std::string` constructor is available because `<stdexcept>` only needs to have a forward declaration of `std::string`. But that's not enough to invoke constructors of `std::exception` (and derivatives) if we don't have a reference to an `std::string` handy.
This is necessary with STLport which only includes a forward declaration of `std::string` in `<stdexcept>`.
=> Make sure std::string constructor is available

include/boost/container/vector.hpp
allocation_command uses expand_{fwd,bwd} flags and its result is later compared with the old pointer, but the old pointer was not passed for reuse.
=> Allow reuse of buffer in reserve with v2 allocator

src/global_resource.cpp
do_allocate() triggered the warning
"code will never be executed [-Wunreachable-code]"
in Clang.
Changed both do_allocate and do_deallocate to keep the existing
similarity.
=> Avoid -Wunreachable-code in do_allocate()

include/boost/container/detail/copy_move_algo.hpp, include/boost/container/vector.hpp
Many of the functions inside copy_move_algo.hpp construct n objects using a specified Allocator, so the number of objects should be given as allocator_traits::size_type. The callers of these functions already use size_type, which currently leads to type conflicts if the InputIterator's difference_type is incompatible (e.g., smaller). 
There is one exception in vector.hpp, where uninitialized_move_alloc_n() is called with a raw pointer difference. I static_casted this to size_type for compatibility.
There are several remaining functions inside copy_move_algo.hpp that use a difference_type parameter, but are independent of an allocator. I changed these to be agnostic of the integral type, as was already done with destroy_alloc_n(). (In fact, all of these functions eventually get called with …
=> Fix parameter types in copy_move_algo.hpp: iterator_traits::difference_type -> allocator_traits::size_type

bench/bench_static_vector.cpp, include/boost/container/detail/advanced_insert_int.hpp, include/boost/container/new_allocator.hpp, include/boost/container/small_vector.hpp, test/map_test.cpp, test/set_test.cpp
I added "Copyright" to `bench_static_vector.cpp` just to make the inspection tool happy.
=> [inspection report] remove tabs and fix copyright notice format

include/boost/container/string.hpp
Conversion from a `basic_string` to a `string_view`, and make all the comparisons work.
Ion - if you like this, I'll work up some tests, too.
=> Add support for `boost::string_view` into `container::basic_string`

include/boost/container/detail/tree.hpp, include/boost/container/map.hpp
I never contributed to boost, I'm not sure what kind of test I should write for this? For now, I ran successfully b2 in `boost/libs/container/test` with this patch applied.
This patch adds a variant of map constructors to avoid useless extra allocator copy when using initializer list
Many existing constructors have this form:
map(std::initializer_list<value_type> il, const Compare& comp = Compare(), const allocator_type& a = allocator_type())
The issue is that a temporary allocator_type is constructed, and
passed to the base class where it is used to copy-constructed the
rebound allocator.
This temporary allocator_type here is always destroyed at the end
of the map() constructor. For stateful allocators this is not
desirable.
The solution is to adopt what libc++ is doing and have to …
=> Remove useless allocator copy in map

build/Jamfile.v2
Have constant link order
to make builds reproducible.
See https://reproducible-builds.org/ for why this is good.
Without this patch g++ would order functions in libboost_container.so.1.64.0
depending on random order of files in the build system's filesystem.
=> Fixed bug Trac #13038

test/vector_test.cpp
silence the deprecation warning
Signed-off-by: Daniela Engert <dani@ngrt.de>
=> std::allocator<void> is deprecated in C++17

include/boost/container/detail/thread_mutex.hpp
fixes msvc warning C5032: "detected #pragma warning(push) with no corresponding #pragma warning(pop)"
=> add missing warning re-enabling include

include/boost/container/flat_map.hpp
Fixed ambiguous CTADs.
Added new macro BOOST_HAS_CTAD_SFINAE to indicate that compiler supports SFINAE to disambiguate CTADs. 
The macro BOOST_HAS_CTAD_SFINAE is currently undefined for all compilers (new versions of gcc may support it, cf. https://github.com/boostorg/container/issues/80, but I cannot check it)
=> Fixed flat_map CTAD

include/boost/container/flat_map.hpp
This PR fixes compilation errors with VS 2017 (/std:c++latest /permissive-).
VS 2017 seems to have a very strict interpretation of  [temp.deduct.guide] (3):
> ... Two deduction guide declarations in the same translation unit for the same class template shall
not have equivalent parameter-declaration-clauses.
Both gcc and clang seem to ignore [temp.deduct.guide] (3), or only considering it for viable CTAD candidates.
NB: There seems to be no explicit explanation, when two parameter-declaration-clauses are equivalent, especially if templates are involved.
=>  merge CTADs with equivalent parameter-declaration-clauses

include/boost/container/detail/flat_tree.hpp
Fix compilation issues on GHS compiler due to function name resolution issues.
Resolves #100, passes all unit tests ([verified on Travis](https://travis-ci.org/boostorg/container/builds/485579071?utm_source=github_status&utm_medium=notification)).  Tested locally on MSVC and Green Hills C++14 Compiler.
=> Fix compilation issues in detail/flat_tree.hpp.

include/boost/container/vector.hpp, test/vector_test.cpp
If merge() is called on an empty vector, then priv_merge_in_new_buffer() will
call deallocate() with size 0 on the old (not-yet-allocated) vector storage.
This violates the Allocator requirement that the pointer passed to deallocate()
must have come from a call to allocate() with the same size.
Fix this by checking old_cap against 0, and also add a unit test for this bug.
=> Fix deallocating never-allocated storage in vector.merge()

include/boost/container/throw_exception.hpp
Mark functions only throwing exceptions or calling `std::abort` with
`BOOST_NORETURN`.
=> Fix -Wmissing-noreturn clang warnings

include/boost/container/new_allocator.hpp
Hi,
You recently merged similar pull requests for similar issues: deprecated copy warnings in gcc 9.
Cheers,
Romain
=> Avoid gcc 9 deprecated copy warnings in new_allocator.hpp.

include/boost/container/detail/copy_move_algo.hpp
When running a program with -fsanitize=integer, I get runtime errors on line 514 of copy_move_algo.hpp due to the way the while loop is written:
[...] boost/container/detail/copy_move_algo.hpp:514:15: runtime error: unsigned integer overflow: 0 - 1 cannot be represented in type 'typename boost::container::allocator_traits<new_allocator<pair<unsigned int, __normal_iterator<const unsigned int *, vector<unsigned int, allocator<unsigned int> > > > > >::size_type' (aka 'unsigned long')
When the loop terminates, n-- will cause unsigned integer overflow in n.  Although the value of n is discarded otherwise, this behavior is likely unwanted and unintentional, thus I'm submitting this PR.
=> Get rid of integer overflow in copy_move_algo.hpp (-fsanitize=integer).

include/boost/container/detail/advanced_insert_int.hpp, include/boost/container/detail/flat_tree.hpp, include/boost/container/list.hpp, include/boost/container/slist.hpp, include/boost/container/static_vector.hpp
Workaround for issue https://github.com/boostorg/container/issues/112
=> Prefix aligned_storage with dtl:: (workaround for msvc 10, 11, 12).

include/boost/container/deque.hpp, include/boost/container/detail/flat_tree.hpp, include/boost/container/detail/tree.hpp, include/boost/container/flat_map.hpp, include/boost/container/flat_set.hpp, include/boost/container/list.hpp, include/boost/container/map.hpp, include/boost/container/set.hpp, include/boost/container/slist.hpp, include/boost/container/stable_vector.hpp, include/boost/container/string.hpp, include/boost/container/vector.hpp, test/deque_test.cpp, test/flat_map_test.cpp, test/flat_set_test.cpp, test/flat_tree_test.cpp, test/list_test.cpp, test/map_test.cpp, test/set_test.cpp, test/slist_test.cpp, test/small_vector_test.cpp, test/stable_vector_test.cpp, test/string_test.cpp, test/tree_test.cpp, test/vector_test.cpp
Most template type parameters 'Allocator' were modified their default type to void since 1.70.0.
These modifications cause has_trivial_destructor_after_move to compile error or yield wrong result.
So, fix them by changing specializations of has_trivial_destructor_after_move.
=> Fix has_trivial_destructor_after_move

include/boost/container/flat_map.hpp, include/boost/container/flat_set.hpp, test/flat_map_test.cpp, test/flat_set_test.cpp
=> With heterogeneous lookup, `equal_range` can result in a range with length greater than 1.

include/boost/container/throw_exception.hpp, test/throw_exception_test.cpp
BOOST_NORETURN is missing for the interface of the throwning methods when BOOST_CONTAINER_USER_DEFINED_THROW_CALLBACKS is defined. Without them you can get a `'noreturn' function does return` warning from g++ at `boost/container/static_vector.hpp:46:4`.
=> Missing BOOST_NORETURN for user defined functions

include/boost/container/detail/value_functors.hpp
`value_less` & `value_equal` were in the global namespace. Moved them into `boost::container`.
=> Remove Classes from Global Namespace

doc/container.qbk
Hi,
It seems that currently, in the documentation, a link to the proposal "minimal incomplete type support"(https://wg21.link/n4510) points to another working draft, "Extensions for Ranges" (https://wg21.link/n4569).
I think it is just a typo, so I'm sending a patch.
Could you check it?
=> fix a link in the documentation

include/boost/container/deque.hpp, test/null_iterators_test.cpp
Previously the iterators of `boost::container::deque` would assert when zero was added to them in at least the following situations:
- The iterator was obtained by a call to `boost::container::deque::begin` and `boost::container::deque::empty` returns `true`
- The iterator was default constructed
This is inconsistent with the way in which the iterators of `boost::container::deque` have behaved historically and is also inconsistent with an understanding of iterators developed by analogy with pointers:
- Adding zero to a null pointer is valid despite the fact the null pointer cannot be dereferenced
- Adding zero to a pointer that is one past the end yields a pointer which is still one past the end and thus which has well defined semantics
Fixed this issue and codified the expected behavior …
=> RandomAccessIterator + 0

include/boost/container/pmr/monotonic_buffer_resource.hpp, include/boost/container/pmr/synchronized_pool_resource.hpp, include/boost/container/pmr/unsynchronized_pool_resource.hpp, src/global_resource.cpp
Use BOOST_OVERRIDE to fix GCC -Wsuggest-override and Clang-tidy modernize-use-override warnings.
=> Use BOOST_OVERRIDE

include/boost/container/container_fwd.hpp
Hi,
IMHO small_flat_[multi]{set|map} are very useful containers but specifying their types is a bit cumbersome: it requires re-specifying the Compare-type and of the value-type of the resp. flat_[multi]{set|map}.
I think providing template aliases for them makes them more user-friendly.
If you think to use this PR I could also extend the documentation.
Tobias
=> alias templates for small_flat_[multi]{set|map} using small_vector as container

include/boost/container/detail/compare_functors.hpp
This patch makes the header able to be built standalone, making possible C++ clang modules builds.
=> Add missing include

include/boost/container/pmr/memory_resource.hpp
Hopefully fixes #165.
Since all member functions of `memory_resource` are either inline or pure, and since the class itself is abstract, there should be no need to dllexport it.
Tested locally on `toolset=msvc-10.0,msvc-11.0,msvc-12.0,msvc-14.0,msvc-14.1,msvc-14.2,clang-win,gcc`.
=> Remove BOOST_CONTAINER_DECL from memory_resource

include/boost/container/deque.hpp, include/boost/container/detail/flat_tree.hpp, include/boost/container/devector.hpp, include/boost/container/flat_map.hpp, include/boost/container/flat_set.hpp, include/boost/container/list.hpp, include/boost/container/map.hpp, include/boost/container/set.hpp, include/boost/container/slist.hpp, include/boost/container/stable_vector.hpp, include/boost/container/static_vector.hpp, include/boost/container/string.hpp, include/boost/container/vector.hpp
This allows `std::is_nothrow_swappable{,_with}` to work properly.
This only touches user-facing classes, with the following exceptions:
- `map`,`set`: only doc changes (with a drive-by missing semicolon fix), `detail::tree` which they derive from already forwards `noexcept` for `swap`.
- `flat_set`: only doc changes for `flat_set` and a change for `detail::flat_tree`, which it derives from to get `swap`.
- `static_vector`: while this adds the forwarding, member `static_vector::swap` is currently never `noexcept`, although it could be for noexcept-swappable and noexcept-move-constructible elements.
- `small_vector`: there is no free swap, and member swap is never `noexcept`, although it could be for noexcept-swappable and noexcept-move-constructible elements. Swapping `small_vector`s of …
=> Add conditional noexcept forwarding from free to member swap functions.

include/boost/container/small_vector.hpp
Since the purpose of this class is to optimize by using static storage, it is important to know what determines whether static or dynamic storage is used.
It looks like there is a doc/container.qbk file that should be updated for this change, but it looks autogenerated and I don't know how to regenerate it.
=> Document small_vector allocation strategy

src/global_resource.cpp
A similar problems for the above (i. e. non-atomic) branch was addressed in #148, yet the default C++11 branch causes segfault with the following stacktrace:
```
(gdb) bt
#0  0x000000000e1c3d28 in boost::container::pmr::memory_resource::allocate (this=0x0, bytes=92, alignment=4)
at boost/container/include/boost/container/pmr/memory_resource.hpp:48
#1  0x000000000e2e9e59 in boost::container::pmr::polymorphic_allocator<float>::allocate (this=0x7fffffffd148, n=23)
at boost/container/include/boost/container/pmr/polymorphic_allocator.hpp:92
#2  0x000000000e2e9cdd in std::__y1::allocator_traits<boost::container::pmr::polymorphic_allocator<float> >::allocate (__a=..., __n=23)
at libcxx/include/__memory/allocator_traits.h:262
#3  0x000000000e2e9b13 in std::__y1::vector<float, …
```
=> Fix using pmr::polymorphic_allocator in pre-main

doc/container.qbk, include/boost/container/detail/copy_move_algo.hpp, test/vector_test.cpp
"POD" is the wrong type trait to determine if something can be safely zero-filled in order to achieve zero initialization. Consider a type like
```
struct POD { int POD::*ptr; };
```
This is a POD; its value initialization needs to value initialize the member, and since it's a pointer, that's zero initialization, and that's setting the pointer to null.
On Itanium, a null pointer to data member is not zero filled; it actually has the value -1u.
Hence, zero-filling via memset(0) a POD object like the one above is erroneous. Unfortunately there is no type trait in C++ that we can use to know if a given datatype can be value initialized by zero-filling -- we can check for trivial constructability, but that's a necessary condition, not a sufficient one (POD above is also trivially …
=> Do not memset(0) POD types

doc/container.qbk
This improves wording of `stored_size` parameter descriptions and also fixes QuickBook syntax.
=> Improve description of stored_size

include/boost/container/detail/config_begin.hpp, src/dlmalloc_2_8_6.c, test/expand_bwd_test_template.hpp
Unsigned negation is a well-defined operation in C and C++ and it is commonly used when doing bit manipulation of unsigned integers, because it builds a high-pass bitmask.
For instance, if `X` is known to be a power of two, `-X` is precisely the mask needed to align a value down to a multiple of `X` by means of a bit-wise `&` operation.
However, it can occasionally be flagging a bug, when the original intent was mathematical negation. For this reason, an explicit fix is preferred to suppressing this warning.
This change fixes all the instances of #303 by changing unsigned negation of the form `-X` to the more explicit `0 - X`, and removes the suppression.
Ran all the tests under "test" and "bench". Fixed two more instances of the warning in one of the unit tests.
I also included a …
=> Fix all instances of MSVC warning C4146 (unsigned negation)

CMakeLists.txt
[`Boost::container` is declared as a header-only library](https://www.boost.org/doc/libs/1_86_0/doc/html/container.html#container.intro.introduction_building_container). So a header-only option is needed.
=> CMake: Add option to use header-only `Boost::container`

include/boost/container/new_allocator.hpp, test/allocator_argument_tester.hpp, test/dummy_test_allocator.hpp, test/explicit_inst_vector_test.cpp
In reference to Issue #306 
I noticed on Ubuntu 24.04 that gcc defines `__cpp_sized_deallocation` but clang does not, unless [opted into](https://bcain-llvm.readthedocs.io/projects/clang/en/release_37/ReleaseNotes/#new-compiler-flags).
So I agree that these checks should be refined to `#if defined()`
=> __cpp_sized_deallocation is not always defined (clang is opt-in) for Issue #306
